Ruby on Rails Capstone Project - Budget App
AliShahSafdari/budget-app pull request #5
Opened 2023-09-14 18:36 UTC by AliShahSafdari

In this PR what I did do?

- Add Splash screen. 

- Create sign-up and log-in pages.
- Create a Home page (categories page)

-  Create Transactions page

-  Create "Add a new category" page

- Create  "Add a new transaction" page

-  Add Testing requirements
 - Create presentation (https://www.loom.com/share/ccb3f7e333c5483d923a6171278c0f0d?sid=1c726ebc-f1d2-4f07-b09a-e5e48fe43a78)

2023-09-14 20:04 UTC, 1GORDON requested changes
##
## Hi @AliShahSafdari ✋

Good job so far!

## Highlights!
- Project functional ✔️
- Good video Presentation ✔️
- Project well deployed ✔️
- Testing are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 20:04 UTC, 1GORDON commented on README.md
>  - Rails
### Since there are a few files changed. i will add all the changes to this file

- [ ] As stated in the project requirements, kindly ensure your project follows the [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) provided.
- [ ] Kindly ensure your login screen is a replica of the login given.
- Your design
![your login page](https://github.com/AliShahSafdari/budget-app/assets/63917725/9eac7bb3-eed6-4139-af97-866b7888335e)
- Given design
![given login page](https://github.com/AliShahSafdari/budget-app/assets/63917725/18378631-1d92-46e1-89f4-6d9221f236de)

- [ ] Kindly ensure your register page is a close replica of the design given
- Your design
![your-sign-up](https://github.com/AliShahSafdari/budget-app/assets/63917725/e2bbc189-92b7-43d1-b4f3-ed353f80a0ee)
- Given design
![given register page](https://github.com/AliShahSafdari/budget-app/assets/63917725/ac658558-15a5-45a6-94d2-ec16bb5b27c8)

- [ ] Kindly ensure the scan button on all the screens is maintained at the bottom of the page just like how it appears in the given design.
- Your design
![your scan button](https://github.com/AliShahSafdari/budget-app/assets/63917725/b02216af-8d5f-4fdf-9afd-a074180ba5b3)
- Given design
![given scan button](https://github.com/AliShahSafdari/budget-app/assets/63917725/9b1b658c-c69c-4757-884c-cbb49df5d7c8)

2023-09-15 01:11 UTC, AliShahSafdari commented
Thanks, I fix it.

2023-09-15 01:12 UTC, AliShahSafdari commented on README.md
>  - Rails
Thanks, I fix it.

2023-09-15 01:23 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @AliShahSafdari, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **[OPTIONAL]** I'm sorry that the previous reviewer didn't point this out, but for future milestones, please consider using Gitflow properly: consider opening a PR from a feature branch with **ALL** the changes to the `development` branch, so we have an easier time reviewing all your code! 🤓 🔧 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 01:30 UTC, merged